export const kpi = [
  {
    id: 9658,
    title: 'Total Sales',
    date: '2023-10-01',
    description:
      'The total value generated by the sale of products or services over a specific period. This KPI reflects the overall financial health of the company.',
  },
  {
    id: 2056,
    title: 'Net Profits',
    date: '2023-10-01',
    description:
      "Measures the company's final profits after deducting all costs, including operating expenses, taxes, and others. It reflects the company's profitability.",
  },
  {
    id: 6854,
    title: 'Conversion Rate',
    date: '2023-10-01',
    description:
      'The percentage of visitors who make a purchase, relative to the total number of website visitors. This KPI measures the effectiveness of sales and marketing strategies.',
  },
  {
    id: 2568,
    title: 'Customer Satisfaction',
    date: '2023-10-01',
    description:
      'A metric that measures how satisfied customers are with a product or service, usually through surveys. A high CSAT score indicates a good customer experience.',
  },
];
