export const kpiDetails = [
  {
    id: 9658,
    title: 'Total Sales',
    value: 5000,
    category: 'Sales',
    description:
      'The total value generated by the sale of products or services over a specific period. This KPI reflects the overall financial health of the company.',
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Metric ID',
        value: '2485',
      },
      {
        name: 'Calculation',
        value: '9495',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Applicable',
      },
      {
        name: 'Last updated',
        value: '2023-10-01',
      },
    ],

    visualsAvailable: [
      { id: '1', name: 'bar', selected: true },
      { id: '2', name: 'pie', selected: true },
      { id: '3', name: 'line', selected: false },
      { id: '4', name: 'doughnut', selected: false },
    ],
  },
  {
    id: 2056,
    title: 'Net Profits',
    value: 200,
    category: 'Customers',
    description:
      "Measures the company's final profits after deducting all costs, including operating expenses, taxes, and others. It reflects the company's profitability.",
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Metric ID',
        value: '2485',
      },
      {
        name: 'Calculation',
        value: '8947',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Not Applicable',
      },
      {
        name: 'Last updated',
        value: '2024-11-01',
      },
    ],
    visualsAvailable: [
      { id: '1', name: 'bar', selected: false },
      { id: '2', name: 'pie', selected: true },
      { id: '3', name: 'line', selected: false },
      { id: '4', name: 'doughnut', selected: true },
    ],
  },
  {
    id: 6854,
    title: 'Conversion Rate',
    value: 3.5,
    category: 'Marketing',
    description:
      'The percentage of visitors who make a purchase, relative to the total number of website visitors. This KPI measures the effectiveness of sales and marketing strategies.',
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Metric ID',
        value: '2485',
      },
      {
        name: 'Calculation',
        value: '3521',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Applicable',
      },
      {
        name: 'Last updated',
        value: '2022-10-01',
      },
    ],
    visualsAvailable: [
      { id: '1', name: 'bar', selected: true },
      { id: '2', name: 'pie', selected: false },
      { id: '3', name: 'line', selected: false },
      { id: '4', name: 'doughnut', selected: true },
    ],
  },
  {
    id: 2568,
    title: 'Customer Satisfaction',
    value: 95,
    category: 'Customer Service',
    description:
      'A metric that measures how satisfied customers are with a product or service, usually through surveys. A high CSAT score indicates a good customer experience.',
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Metric ID',
        value: '2485',
      },
      {
        name: 'Calculation',
        value: '2485',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Applicable',
      },
      {
        name: 'Last updated',
        value: '2023-10-01',
      },
    ],
    visualsAvailable: [
      { id: '1', name: 'bar', selected: true },
      { id: '2', name: 'pie', selected: true },
      { id: '3', name: 'line', selected: false },
      { id: '4', name: 'doughnut', selected: true },
    ],
  },
];
