export const storyBoardsDetails = [
  {
    id: 301,
    title: 'Total Sales',
    value: 5000,
    category: 'Sales',
    description:
      'The total value generated by the sale of products or services over a specific period. This KPI reflects the overall financial health of the company.',
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Coupled KPI',
        value: 'On track',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Applicable',
      },
      {
        name: 'Pages No.',
        value: '6',
      },
      {
        name: 'Last updated',
        value: '2023-10-01',
      },
    ],
  },
  {
    id: 302,
    title: 'Net Profits',
    value: 200,
    category: 'Customers',
    description:
      "Measures the company's final profits after deducting all costs, including operating expenses, taxes, and others. It reflects the company's profitability.",
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Coupled KPI',
        value: 'On track',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Applicable',
      },
      {
        name: 'Pages No.',
        value: '6',
      },
      {
        name: 'Last updated',
        value: '2023-10-01',
      },
    ],
  },
  {
    id: 303,
    title: 'Conversion Rate',
    value: 3.5,
    category: 'Marketing',
    description:
      'The percentage of visitors who make a purchase, relative to the total number of website visitors. This KPI measures the effectiveness of sales and marketing strategies.',
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Coupled KPI',
        value: 'On track',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Applicable',
      },
      {
        name: 'Pages No.',
        value: '6',
      },
      {
        name: 'Last updated',
        value: '2023-10-01',
      },
    ],
  },
  {
    id: 304,
    title: 'Customer Satisfaction',
    value: 95,
    category: 'Customer Service',
    description:
      'A metric that measures how satisfied customers are with a product or service, usually through surveys. A high CSAT score indicates a good customer experience.',
    businessQuestions: [
      {
        id: '1',
        name: 'Question 1',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '2',
        name: 'Question 2',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '3',
        name: 'Question 3',
        description: 'Short description of the item goes nicely here',
      },
      {
        id: '4',
        name: 'Question 4',
        description: 'Short description of the item goes nicely here',
      },
    ],
    metricIds: [
      { id: '1', name: '#ppa' },
      { id: '2', name: '#ppa' },
      { id: '3', name: '#ppa' },
    ],
    data: [
      {
        name: 'Coupled KPI',
        value: 'On track',
      },
      {
        name: 'Affiliate Applicability',
        value: 'Not Applicable',
      },
      {
        name: 'Pages No.',
        value: '6',
      },
      {
        name: 'Last updated',
        value: '2023-10-01',
      },
    ],
  },
];
